# Medium Difficulty CI Workflow
# Runs on pushes or pull requests
# Adds caching and separates test & build jobs

name: Medium CI Workflow

# When to run
on:
  push:
    branches:
      - main
      - dev # Also run when pushing to 'dev'
  pull_request:
    branches:
      - main

# Jobs are independent tasks that run in parallel or one-by-one
#! currently this pipeline has 2 jobs - "test-job" and "build-job"
jobs:
  test: # Job 1: run tests
    runs-on: ubuntu-latest
    env: # Environment variables
      NODE_ENV: test

    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Cache node_modules # Speed up installs
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build: # Job 2: build the project
    runs-on: ubuntu-latest
    needs: test # Only run build if tests pass

    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
